GIRAPH-136: Error message for bin/giraph could be improved.
git-svn-id: https://svn.apache.org/repos/asf/incubator/giraph/trunk@1240303 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/bin/giraph b/bin/giraph
--- a/bin/giraph
+++ b/bin/giraph
@@ -15,6 +15,14 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+# friendly message for those who forget to tell us what to do
+if [ $# = 0 ]; then
+  echo "Usage: giraph [-D<Hadoop property>] <jar containing vertex> <parameters to jar>"
+  echo "At a minimum one must provide a path to the jar containing the vertex to be executed."
+  exit 1
+fi
+
+
 # resolve links - $0 may be a softlink
 THIS="$0"
 while [ -h "$THIS" ]; do
@@ -31,7 +39,7 @@ done
 THIS_DIR=`dirname "$THIS"`
 GIRAPH_HOME=`cd "$THIS_DIR/.." ; pwd`
 
-# extra properites to send straight to Hadoop
+# extra properties to send straight to Hadoop
 HADOOP_PROPERTIES=
 while [ $1 ] && [ ${1:0:2} == "-D" ] ; do
     HADOOP_PROPERTIES="$1 $HADOOP_PROPERTIES"
@@ -42,29 +50,46 @@ USER_JAR=$1
 shift
 
 if [ ! -e "$USER_JAR" ]; then
-  echo "Can't find user jar to execute."
+  echo "Can't find user jar (${USER_JAR}) to execute."
   exit 1
 fi
 
 # add user jar to classpath
 CLASSPATH=${USER_JAR}
 
+CLASS=org.apache.giraph.GiraphRunner
+
 # so that filenames w/ spaces are handled correctly in loops below
 IFS=
 
 # add release dependencies to CLASSPATH
-for f in $GIRAPH_HOME/lib/*.jar; do
-  CLASSPATH=${CLASSPATH}:$f;
-done
+if [ -d "$GIRAPH_HOME/lib" ]; then
+	for f in $GIRAPH_HOME/lib/*.jar; do
+	  CLASSPATH=${CLASSPATH}:$f;
+	done
 
-CLASS=org.apache.giraph.GiraphRunner
-
-for f in $GIRAPH_HOME/lib/giraph*.jar ; do
-  if [ -e "$f" ]; then
-    JAR=$f
-  fi
-done
-
+	for f in $GIRAPH_HOME/lib/giraph*.jar ; do
+	  if [ -e "$f" ]; then
+	    JAR=$f
+	    break
+	  fi
+	done
+else
+	echo "No lib directory, assuming dev environment"
+	if [ ! -d "$GIRAPH_HOME/target" ]; then
+		echo "No target directory. Build Giraph jar before proceeding."
+		exit 1
+	fi
+	
+	CLASSPATH=`mvn dependency:build-classpath | grep -v "[INFO]"`
+	
+	for f in $GIRAPH_HOME/target/giraph*.jar ; do
+	  if [ -e "$f" ]; then
+	    JAR=$f
+	    break
+	  fi
+	done
+fi
 # restore ordinary behaviour
 unset IFS
 
